[project]
name = "tf2-lm-gru-shakespeare-text-generation"
version = "0.1.0"
description = "Character-level language model with a stateful GRU that learns Shakespeare's text and generates new text, built with TensorFlow 2 (Keras)."
readme = "README.md"
authors = [
    { name = "Diego Ramirez Rosas", email = "ramirezgrosas@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "tensorflow>=2.21.0",
]

[project.scripts]
tf2-lm-gru-shakespeare-text-generation = "tf2_lm_gru_shakespeare_text_generation:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
